name: 13-Artifacts

on:
  workflow_dispatch

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact

    steps:
    - name: Download web-app content
      uses: actions/download-artifact@v4
      with:
        name: Package
           
    - name: View content
      run: ls -R
