name: 21-CI Pipeline

on:
  workflow_dispatch:
    inputs:
      java-version:
        type: choice
        options:
          - 11
          - 14
          - 17

jobs:
  intialize:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.set-java-version.outputs.java-version }}
    steps:
      - name: Intialize project
        id: set-java-version
        run: echo "::set-output name=java-version::${{ github.event.inputs.java-version }}"

  build:
    runs-on: ubuntu-latest
    needs: intialize
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ needs.intialize.outputs.java-version }}
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true

    - name: Upload jar to folder
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/

  test:
    runs-on: ubuntu-latest
    needs: intialize
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ needs.intialize.outputs.java-version }}
        cache: 'maven'
    - name: Test with Maven
      run: mvn -B test

  release:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download web-app content
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: target/
  
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
          
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip

  image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download web-app content
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: target/

      - name: Build Docker image
        run: docker build -t username/todoapp .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push username/todoapp
