name: Contexts - github


on:
 workflow_dispatch:


jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: Display Event Information
     run: |
       echo "Event Name: ${{ github.event_name }}"
       echo "Ref: ${{ github.ref }}"
       echo "SHA: ${{ github.sha }}"
       echo "Actor: ${{ github.actor }}"
       echo "Workflow: ${{ github.workflow }}"
       echo "Run ID: ${{ github.run_id }}"
       echo "Run number: ${{ github.run_number }}"
